### ISSUE TITLE
Error: list index out of range

### ISSUE THREAD

**Issue by bramvera** [theUpsider/ComfyUI-Styles_CSV_Loader#1]
got error
```
styles_csv_loader.py", line 42, in INPUT_TYPES
    "styles": (list(cls.styles_csv.keys()),),
AttributeError: 'list' object has no attribute 'keys'
Error: list index out of range
```

**Comment by theUpsider** [comment]
You have to name the file: styles.csv also check if the format in the file is correct. If you manually saved the file in excel it likely got corrupted.

**Comment by brumie** [comment]
the same file I'm using with A1111, working fine on A1111

**Comment by brumie** [comment]
i replaced line 42 with this 
`"styles": (list(style[0] for style in cls.styles_csv),),`
and fixed my error

**Comment by theUpsider** [comment]
Thanks for the proposal. Will look into this as soon as I can.

**Comment by theUpsider** [comment]
@brumie I worked in your fix. Please report if it works :)

**Comment by brumie** [comment]
> @brumie I worked in your fix. Please report if it works :)

thanks, got an error
```
Error occurred when executing Load Styles CSV:

list indices must be integers or slices, not str
```

**Comment by cjps-br** [comment]
the same error was occurring in my installation. I then noticed that the style names were not in quotes. I adjusted the .scv file to put quotes around all the style names, but I had to return line 42 to the previous version

("styles": (list(cls.styles_csv.keys()),),)

for everything to work.

**Comment by MarcelMoczarski** [comment]
thanks for the extension.

in "styles": (list(style[0] for style in cls.styles_csv),)" should indeed be "("styles": (list(cls.styles_csv.keys()),)," as mentioned above, otherwise style[0] returns the first letter of each dict key instead of the complete variable name.
